### ISSUE TITLE
Reading Float (Real) Values from the OPC UA Server

### ISSUE THREAD

**Issue by indumatec** [gerardogrisolini/ZenOPCUA#1]
First of all: Great work!

I tried to read out a Float (Real) Value from the OPC UA Server and get the error:
NIO-ELT-0-#0 (9): Fatal error: Array index is out of range in the ReadResponse.swift at Line 45.

Can you help?

Thanks in advance!

<img width="473" alt="Bildschirmfoto 2021-09-09 um 11 04 23" src="https://user-images.githubusercontent.com/89501674/132656981-4766a4f9-0de1-48c0-9a37-26233fc5a17f.png">

**Comment by gerardogrisolini** [comment]
Hi, I'm glad it's useful to you.
I don't have time to work on it, but I made you a quick change that should fix the bug.
Release v2.0.10
Let me know if it works

**Comment by indumatec** [comment]
Hi,
thanks for the very fast respond.

I updated, but then there was a compiler error for the len statement on line .
So I changed to len.int:
Now I cannot read any of the datapoints:

PolicyId Anonymous-[0]-None-None
Client activated
Error: Invalid variant 64 for DataType
2784531420
142
Error: Invalid variant 91 for DataType
2784531575
142
Error: Invalid variant 228 for DataType
2784531727
142
Error: Invalid variant 69 for DataType
2784531880
142
Error: Invalid variant 174 for DataType
2784532032
142
Error: Invalid variant 65 for DataType
2784532185
142
Error: Invalid variant 59 for DataType
2784532338
142
Error: Invalid variant 167 for DataType
2784532491
142

The values above are count and index.

BTW:
The following datatypes work seamless:
BOOL, BYTE, INT, WORD, DATETIME.
false
[52]
-1278
64258
true
[53]
-1277
64259
false

Any advise?

Thanks!
Gilbert

**Comment by gerardogrisolini** [comment]
Hello,
sorry for the last change, I tried to correct on the fly ... but it was better if I was still !!!
I just released version 2.0.11 which fixes the Float problem.

**Comment by indumatec** [comment]
Hello Gerardo,

perfect, it works seamless:

BOOL: true
BYTE: [149]
INT: 27009
REAL: 1075585.0
REAL: 0.7512804
WORD: 27009

false
[150]
27010
1075586.0
0.7173561
27010

Thanks again for your great work.
I will close the issue :-)
Gilbert
